### ISSUE TITLE
how can i solve this problem

### ISSUE THREAD

**Issue by Fadexboss** [sczhou/ProPainter#1]
![Ekran görüntüsü 2023-09-08 003445](https://github.com/sczhou/ProPainter/assets/80221984/30d3a337-ad51-40fd-81ce-a5ce3254f4ca)

**Comment by dustydust** [comment]
@Fadexboss in this environment.yaml list dependencies related to OS, I suppose author have Linux. So in Windows it couldn't work

**Comment by Fadexboss** [comment]
by manually setting the virtual environment and can I import libraries like requirements.txt

**Comment by dustydust** [comment]
At the moment I have the same issue and trying to resolve it on Windows

**Comment by dustydust** [comment]
requirements.txt for windows with python=3.7

addict==2.4.0
av==10.0.0
certifi==2023.7.22
charset-normalizer==3.2.0
colorama==0.4.6
cycler==0.11.0
decorator==4.4.2
defusedxml==0.7.1
einops==0.6.1
fonttools==4.38.0
future==0.18.3
idna==3.4
imageio==2.31.2
importlib-metadata==6.7.0
kiwisolver==1.4.5
matplotlib==3.5.3
mmcv-full==1.4.8
networkx==2.5.1
numpy==1.21.6
onnx==1.9.0
opencv-python==4.8.0.76
packaging==23.1
Pillow==9.5.0
platformdirs==3.10.0
protobuf==3.17.0
pyparsing==3.1.1
python-dateutil==2.8.2
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
scipy==1.7.3
six==1.16.0
test-generator==0.1.1
tomli==2.0.1
torch==1.6.0+cu101
torchvision==0.7.0+cu101
tqdm==4.66.1
typing_extensions==4.7.1
urllib3==2.0.4
yapf==0.40.1
zipp==3.15.0

**Comment by Fadexboss** [comment]
Thank you for sharing your problem solving step with me, I will investigate from where you left off.
