### ISSUE TITLE
在视频去水印的样例中，需要输入视频和要去除的水印图片

### ISSUE THREAD

**Issue by terry** [sczhou/ProPainter#12]
在视频去水印的样例中，需要输入视频和要去除的水印图片。这个要去除的水印图片是否是必须的？如果是必须的，除了人工标注之外，是否有好的自动获取的方式？

**Comment by sczhou** [comment]
Mask图片都是必须的，对于去水印这个任务，目前没有更好的方式；对于物体去除，我们后续会提供一个demo实现通过点击物体获取Mask。

Duplicate issue with #2
