### ISSUE TITLE
Create Conda Environment and Install Dependencies

### ISSUE THREAD

**Issue by shinyrico** [sczhou/ProPainter#13]
When I type conda env create -f environment.yaml then
ninja: build stopped: subcommand failed.
RuntimeError: Error compiling objects for extension
CondaEnvException: Pip failed
How to solve this problem？ thank you！

**Comment by Fadexboss** [comment]
https://github.com/sczhou/ProPainter/issues/7#issuecomment-1722295467
works for me!

**Comment by sczhou** [comment]
Hi @shinyrico , I just simply the installation by removing the mmcv and update the installation steps, please check it out:
https://github.com/sczhou/ProPainter#dependencies-and-installation

Same issues: #1 #7 #13 #20
