### ISSUE TITLE
环境安装不了呢？大家呢？

### ISSUE THREAD

**Issue by reaway** [sczhou/ProPainter#20]
我用梯子和不用梯子都安装不了环境呢？你们能成功？
![H$2_%X`HS_@8OEEW@%(KLKP](https://github.com/sczhou/ProPainter/assets/60423559/23322c3d-dcdc-4ca5-9bf3-d807b61caed2)

**Comment by Fadexboss** [comment]
https://github.com/sczhou/ProPainter/issues/7#issuecomment-1722295467
works for me

**Comment by yw-2020** [comment]
我也遇到了同样的问题，windows

**Comment by sczhou** [comment]
Hi @reaway @yw-2020 , 我们刚刚更新了安装方式，可以尝试一下新的安装。

**Comment by yw-2020** [comment]
可以了，优秀
