### ISSUE TITLE
Why configs/train_e2fgvi.json?

### ISSUE THREAD

**Issue by Roowenliang** [sczhou/ProPainter#22]
Awesome algorithm! I tested the inference code and it works great!

I have a question on the train.py. 
Does your training code need anything from E2FGVI code?
parser = argparse.ArgumentParser(description='E2FGVI')
parser.add_argument('-c',
                    '--config',
                    default='configs/train_e2fgvi.json',
                    type=str)

**Comment by sczhou** [comment]
Thank you @Roowenliang for reporting this typo.

Since this work was built on the E2FGVI's repo, I forgot to change default argument, but it should not affect the training.
I will fix it then. Thanks!
