### ISSUE TITLE
Reduce the frames of sub-videos --subvideo_lentgh (default 80), which effectively decouples GPU memory costs and video length. (coming soon!)

### ISSUE THREAD

**Issue by fucksmile** [sczhou/ProPainter#23]
你好Team,
是不是能把长视频（十分钟以上）每10帧处理一次，这样就不需要把长视频分割成大量小文件，然后批量处理，处理完然后再拼接这样挺麻烦的还容易出错

谢谢！

**Comment by sczhou** [comment]
你好，我们目前在inference code中已经实现了自动subvideo切段（默认80帧），主要解决GPU memory问题，处理完后不需要用户手动去拼接。不过如果是特别长的视频（10分钟以上）建议手动切成1分钟以内的视频。

**Comment by fucksmile** [comment]
给力，感谢！
