### ISSUE TITLE
What are the data formats of  "flow_root": "your_flow_root"  for training

### ISSUE THREAD

**Issue by Roowenliang** [sczhou/ProPainter#24]
I assume that I need to preprocess all the videos to get the forward and backward optical flows and save them somewhere("your_flow_root") for the model trainings. 
Could you please share the pre-processing code or tell us what formats we need to follow?

Thanks

**Comment by sczhou** [comment]
Hi @Roowenliang, if you set `load_flow` to 0 in the training JSON file, you don't need to precompute optical flow for the training dataset. However, if you want to speed up the training process, you can calculate optical flow in advance using the following command:

```
# Compute optical flow for training dataset
python scripts/compute_flow.py --root_path <dataset_root> --save_path <save_flow_root> --height 240 --width 432
```
