### ISSUE TITLE
A bug or using the wrong package (training)

### ISSUE THREAD

**Issue by Roowenliang** [sczhou/ProPainter#29]
Hi Mr.  Zhou
Thanks for answering my two questions. Got another one. 
I came across an issue at line #291 "if flows_f == 'None' or flows_b == 'None':"  in trainer_flow_w_edges.py when I try to run the training code. 
The issue is that "flows_f" and "flows_b" are actually list, so flows_f == 'None' always return false even when "load_flow": is set to "0" in the json file. 
The training started running after changing that line to "if flows_f[0] == 'None' or flows_b[0] == 'None':" 

Not sure if this issue is related to the python packages I'm using or not? 
Also is there any potential issues for the change  "if flows_f[0] == 'None' or flows_b[0] == 'None':" ?

Thanks!

**Comment by sczhou** [comment]
Hi @Roowenliang , yes, you are right, it should be a bug, and you need to change `flows_f, flows_b` to `flows_f[0], flows_b[0]` .

I have fixed this bug, you can just pull the code. Thanks!

**Comment by Roowenliang** [comment]
Thanks! Awesome work.
