### ISSUE TITLE
crash when running " python train.py -c configs/train_propainter.json"

### ISSUE THREAD

**Issue by Roowenliang** [sczhou/ProPainter#30]
Hi Mr. Zhou,
One more training related question, sorry.

The training crashes when I try "python train.py -c configs/train_propainter.json". Here is what I did:
1.  Update the json file for the "video_root"
2. Pointing to the downloaded flow completion model -        self.fix_flow_complete = RecurrentFlowCompleteNet('/mnt/lustre/sczhou/VQGANs/CodeMOVI/experiments_model/recurrent_flow_completion_v5_train_flowcomp_v5/gen_760000.pth')
+        self.fix_flow_complete = RecurrentFlowCompleteNet('**/weights/recurrent_flow_completion.pth')
3. run the training.
But I see this:
File "*/Documents/MyCode/Inpainting/ProPainter/model/propainter.py", line 354, in forward
    _, _, local_feat, _ = self.feat_prop_module(local_feat, ds_flows_f, ds_flows_b, prop_mask_in, interpolation)
  File "*/anaconda3/envs/propainter3_8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "*/Documents/MyCode/Inpainting/ProPainter/model/propainter.py", line 183, in forward
    outputs = self.fuse(torch.cat([outputs_b, outputs_f, mask_in], dim=1)) + x.view(-1, c, h, w)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

I haven't had the chance to trace the code yet, just in case, to you,  it is a super easy fix :-)

**Comment by Roowenliang** [comment]
fixed it

**Comment by Suyimu** [comment]
I'm having the same problem, please tell me how it was fixed

**Comment by Suyimu** [comment]
Solved, just type "x = x.contiguous()" before line 184
