### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by michaelxmchn** [sczhou/ProPainter#43]
D:\test\propainter\ProPainter>python inference_propainter.py --video inputs/object_removal/bmx-trees --mask inputs/object_removal/bmx-trees_mask
Traceback (most recent call last):
  File "D:\test\propainter\ProPainter\inference_propainter.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by sczhou** [comment]
Please install `cv2` first
