### ISSUE TITLE
视频分辨率不能高于432*240？

### ISSUE THREAD

**Issue by gyy0611** [sczhou/ProPainter#5]
想请问一下，如果1080P的视频是不是不可以去除水印或者物体呢？另外一个题外话，不会PS的遮罩怎么弄，有没有可以告知一下

**Comment by sczhou** [comment]
你好，

1. 可以高于432x240,，video inpainting的模型比较耗memory，所以默认会resize到432x240，如果想测试更高尺度，可以根据GPU memory调节`--size`：https://github.com/sczhou/ProPainter/blob/main/inference_propainter.py#L177

2. 对于去水印，目前只有自己用PS或者其他软件自己获得mask；对于去物体，我们后面会提供一个Gradio demo自动获取指定物体的 mask （参考回答：#2）
