### ISSUE TITLE
custom the output resolution

### ISSUE THREAD

**Issue by Note-Liu** [sczhou/ProPainter#6]
Can the ProPainter custom the output resolution like E2FGVI?

**Comment by sczhou** [comment]
Sure, you can set `--size` in your command.

Please refer to the arguments in inference code: https://github.com/sczhou/ProPainter/blob/main/inference_propainter.py#L177

**Comment by 21pl** [comment]
there seems to be an issue trying to set the tuple with --size from the command line. Tried x, y and x y and (x y) and (x,y) but always seems to error out.
I added the ability to read the input dimensions and set the size internally but the inference quickly runs out of GPU ram (it wanted 96 G for 1920x1080 input)
Also if the new resolution is not divisible by 8 on width and height an error is generated. Could pad the input and then unpad the output?

**Comment by Note-Liu** [comment]
> there seems to be an issue trying to set the tuple with --size from the command line. Tried x, y and x y and (x y) and (x,y) but always seems to error out. I added the ability to read the input dimensions and set the size internally but the inference quickly runs out of GPU ram (it wanted 96 G for 1920x1080 input) Also if the new resolution is not divisible by 8 on width and height an error is generated. Could pad the input and then unpad the output?

The output of 1080P consumes a lot of GPU graphics memory. Unless your GPU graphics memory is large enough, you need to reduce the output resolution.
