### ISSUE TITLE
Is it possible to make the size flexible?

### ISSUE THREAD

**Issue by XinyueZ** [sczhou/ProPainter#8]
Hey everyone,

I have utilized `--size 228 512` to achieve the right dimensions, but an error occurs when I begin processing.

`RuntimeError: grid_sampler(): expected grid and input to have the same batch size, but received input with sizes [109504, 1, 64, 29] and grid with sizes [105728, 9, 9, 2]`

I'm not sure about the specific rule that should be followed here.

thx

**Comment by 21pl** [comment]
Also getting this error . Looks like the resolution h & w have to be divisible by 8 to work with RAFT ?

**Comment by sczhou** [comment]
Hi @XinyueZ @21pl , thank you for reminding us of this error, let me check the code and fix it soon.
