### ISSUE TITLE
Why is there always flickering?

### ISSUE THREAD

**Issue by XinyueZ** [sczhou/ProPainter#9]
Hey, 

after processing my result flickered all the time.
Did I forget to set something? 
（I was using SAM and Xmem to get masks.)

my origin video:

https://github.com/sczhou/ProPainter/assets/7869833/12047cb5-c8d9-4637-93a8-38e5c4de8af6

result:

https://github.com/sczhou/ProPainter/assets/7869833/da189a13-13c8-4379-a6df-608028cfba88

**Comment by Fadexboss** [comment]
You can divide the video into frames, delete the broken ones, and then add extra scenes with rife.

**Comment by Fadexboss** [comment]
You can save the video as a frame and delete the broken scenes, then add extra scenes with rife.

**Comment by XinyueZ** [comment]
But what exactly do you mean by "broken scenes"?
How can one identify them?
Could you offer slightly more clarification?

**Comment by Fadexboss** [comment]
> @Fadexboss  But what exactly do you mean by "broken scenes"?
> How can one identify them?
> Could you offer slightly more clarification?

Save an entire video as a frame.  Then delete the faulty scenes in it.  Then convert it back to video and increase the fps with rife.

**Comment by XinyueZ** [comment]
@Fadexboss Thank you for your advice, but this seems to require manual post-processing. What is the root cause of this issue and is there a solution to prevent it?

**Comment by XinyueZ** [comment]
@sczhou do you have idea of it?

**Comment by asasas234** [comment]
@XinyueZ  I encountered a similar problem yesterday, and my solution was to re-encode the video.

**Comment by XinyueZ** [comment]
` re-encode the video.` , do you mean the "source video"?

**Comment by asasas234** [comment]
@XinyueZ No, I sliced the video and replaced the sound in some of the clips. When I merged these clips together, I noticed that there was also a shaking issue with the video footage. So, I re-encoded it and fixed the problem.

**Comment by XinyueZ** [comment]
@asasas234 thanks, so, the problem is caused by the video that contains the sound?   😏 ?

**Comment by asasas234** [comment]
@XinyueZ I suspect it is caused by issues such as inconsistent bitrates between the processed video and the original video.

**Comment by XinyueZ** [comment]
@asasas234 well, that means, the model does not work for the general videos or does it only work for the sample video 😄 ?

**Comment by asasas234** [comment]
@XinyueZ You misunderstood, what I meant was that I encountered flickering issues when processing videos with ffmpeg before, but it has nothing to do with this model. However, I speculate that the results produced by this model might be related to the video bitrate.

**Comment by XinyueZ** [comment]
I did not use `ffmpeg` to process video before and after, they were handled by  `cv2` 😄

**Comment by fu-jianhua** [comment]
I also encountered this issue, which is caused by the incorrect naming of the input video and mask. It should be the same as the given example，such as 00001.jpg

**Comment by XinyueZ** [comment]
> I also encountered this issue, which is caused by the incorrect naming of the input video and mask. It should be the same as the given example，such as 00001.jpg

I think that this is a bug
@sczhou , pls take a look at it.

**Comment by fu-jianhua** [comment]
![企业微信截图_16952873011651](https://github.com/sczhou/ProPainter/assets/77963920/cb08a9bf-c5a6-4c9f-b9c3-e20ffc832faf)

I think you also have a naming issue because the flickering areas in your result video are discontinuous

**Comment by asasas234** [comment]
http://youtube-dubbing.com/ I would like to introduce two Chrome extensions that I have developed here. They can automatically translate foreign YouTube videos into Chinese or other specified languages while watching. It is not a subtitle translation plugin, but it directly plays the translated content. Compared to subtitle plugins, it is more convenient. @XinyueZ @fu-jianhua

**Comment by zaojue405** [comment]
can you tell me what tool you used to make mask?Do I need to draw the mask one frame by one frame?

**Comment by XinyueZ** [comment]
Thank @fu-jianhua , the issue has been solved , I close the ticket.

**Comment by zaojue405** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到你的来信。我将尽快给您回复。
